name: webooxx
version: 9
handle:

- rewrite: if( path ~ "^/((?!index\.php)[^/]*)$" ) goto "/index.php?m=index&a=$1"
- rewrite: if( path ~ "^/((?!index\.php)[^/]*)/([^/]*)$" ) goto "/index.php?m=$1&a=$2"